### ISSUE TITLE
fig文件缺失

### ISSUE THREAD

**Issue by Jinfeng50** [zaocan666/Image-dehazing-using-Using-Dark-Channel-Prior-and-AOD-network#1]
你好！
运行暗原色先验方法的UI代码时，仅有mygui.m是无法正常启动的，需要有mygui.fig文件的配合，但工程中并没有提供，请问可以更新一下代码吗？

**Comment by zaocan666** [comment]
抱歉，我看了一下网盘发现没有留存这个fig文件
其实就是很简单的界面，输入图像然后执行算法
